---
title: "ATNDで見るTokyo.R"
author: "Shinya Uryu"
date: "2015年2月21日"
output: html_document
---

```{r using_pkg}
library("dplyr", warn.conflicts = FALSE)
library("ggplot2")
library("gridExtra")
library("rvest")
library("stringr")
library("RCurl") # getURL
library("RJSONIO") # fromJSON ##rjson pkgではNULLをNAとしない
library("rlist")
library("DT")
library("ggthemes")
# library(extrafont)
```

```{r setup}
# theme_set(theme_classic(base_size = 18, base_family = "Helvetica"))
```

# ATNDに掲載されているTokyo.Rの情報を取得する

```{r gen_get_url, eval=FALSE}
url <- html("https://atnd.org/events/61553") %>% 
  html_nodes("#post-body p a") %>% 
  html_attr("href")
url <- url[3:47] # 不要なリンクを削除（第1回から第45回までが解析対象）
# http://atnd.org/events/の部分を削除
atnd.id <- str_sub(url, 24, 40)

seminar <- html("https://atnd.org/events/61553") %>% 
  html_nodes("#post-body p a") %>% 
  html_text()
seminar <- seminar[3:47]
# cbind(url, atnd.id) %>% cbind(seminar) %>% 
#   write.csv("data/tokyor_event.csv", row.names = FALSE)
```

```{r SETUP_EVENT_DATA}
df <- read.csv("data/tokyor_event.csv", header = TRUE)
```

```{r, eval=FALSE}
# ATNDのイベントサーチAPIを叩く
base.url <- c("http://api.atnd.org/events/")
p1 <- getURL(paste(base.url, "?event_id=", atnd.id[1], "&format=json", sep = "")) %>% fromJSON(nullValue = NA)
```

# ATNDの出欠確認APIを叩いて参加者の情報を取得

```{r SETUP_ENTRY_DATA}
base.url <- c("http://api.atnd.org/events/users/")
#getURL(paste(base.url, "?event_id=", df$atnd.id[1], sep = ""))
# p1 <- getURL(paste(base.url, "?event_id=", df$atnd.id[1], "&format=json", sep = "")) %>% fromJSON(nullValue = NA)
# str(p1)
# p2 <- p1$events[[1]]$event$users # 20人分のデータ
# p2 <- data.frame(matrix(unlist(p2), ncol = 4, byrow = T))

for (i in 1:45) {
  tmp <- getURL(paste(base.url, "?event_id=", df$atnd.id[i], "&format=json", sep = "")) %>% 
    fromJSON(nullValue = NA)
  tmp <- tmp$events[[1]]$event$users
  tmp <- data.frame(matrix(unlist(tmp), ncol = 4, byrow = T))
  
  number <- i
  tmp <- cbind(number, tmp)
  assign(paste("df", i, sep = ""), tmp) # データフレームを生成
}

# うーんこの。もうちょいすまーとな方法があるはず...
df <- rbind(df1, df2) %>% rbind(df3) %>% rbind(df4) %>% rbind(df5) %>% 
  rbind(df6) %>% rbind(df7) %>% rbind(df8) %>% rbind(df9) %>% rbind(df10) %>% 
  rbind(df11) %>% rbind(df12) %>% rbind(df13) %>% rbind(df14) %>% rbind(df15) %>% 
  rbind(df16) %>% rbind(df17) %>% rbind(df18) %>% rbind(df19) %>% rbind(df20) %>% 
  rbind(df21) %>% rbind(df22) %>% rbind(df23) %>% rbind(df24) %>% rbind(df25) %>% 
  rbind(df26) %>% rbind(df27) %>% rbind(df28) %>% rbind(df29) %>% rbind(df30) %>% 
  rbind(df31) %>% rbind(df32) %>% rbind(df33) %>% rbind(df34) %>% rbind(df35) %>% 
  rbind(df36) %>% rbind(df37) %>% rbind(df38) %>% rbind(df39) %>% rbind(df40) %>% 
  rbind(df41) %>% rbind(df42) %>% rbind(df43) %>% rbind(df44) %>% rbind(df45)

colnames(df) <- c("Number", "ID", "Name", "Twitter", "Status")
# Number... 第X回
# ID... ATND ID
# Name... ATNDでのユーザー名
# Twitter... Twitterのユーザー名
# Status... 0 -> 欠席、1 -> 出席
```

## 参加回数での順位

```{r}
df.participation <- group_by(df) %>% count(Name, sort = TRUE)
df.participation.tw <- group_by(df) %>% count(Twitter, sort = TRUE) %>% na.omit() %>% 
  mutate(Name = Twitter)
df <- left_join(df.participation, df.participation.tw, by = "Name")
colnames(df) <- c("Name", "Entry", "Twitter", "Entry from Twitter")
```

```{r, fig.width = 10, fig.align = 'center', eval=TRUE}
p1 <- head(df.participation, 20) %>% droplevels() %$%
  ggplot(., aes(x = reorder(Name, -n), y = n)) + 
  geom_bar(stat = "identity", fill = "#F7417A") + 
  geom_text(aes(label = n), colour = "#FFFFFF", vjust = -0.6) +
  theme(axis.text.x = element_text(size = 12, angle = 50, vjust = 0.5)) + 
  xlab("ATND user name") + ylab("Entry") + ggtitle("Top 20 ATND user \n joined in Tokyo.R") +
  scale_y_continuous(limits = c(0, 30)) +
  theme_hc(bgcolor = "darkunica")

p2 <- head(df.participation.tw, 20) %>% droplevels() %$%
  ggplot(., aes(x = reorder(Name, -n), y = n)) + 
  geom_bar(stat = "identity", fill = "#17CCB7") + 
  geom_text(aes(label = n), colour = "#FFFFFF", vjust = -0.6) +
  theme(axis.text.x = element_text(size = 12, angle = 50, vjust = 0.5)) + 
  xlab("Twitter user name") + ylab("Entry") + ggtitle("Top 20 Twitter user \n joined in Tokyo.R") +
  scale_y_continuous(limits = c(0, 30)) +
  theme_hc(bgcolor = "darkunica")
grid.arrange(p1, p2, ncol = 2)
```

> ATND内で複数のユーザー名を使っている場合もそれぞれ別ユーザーとして算出。ほとんど違いはない

```{r, eval=FALSE, echo=FALSE}
# 1. (28)... yokkuns(tw:yokkuns)
# 1. (28)... aad34210
# 3. (25)... bob3(tw:bob3bob3)
# 4. (23)... teramonagi(tw:teramonagi)
# 5. (20)... mikado_hito(tw:mikado_hito)
# 5. (20)... Hiro_macchan(tw:Hiro_macchan)
# 7. (19)... manozo(tw:manozo)
# 7. (19)... atg
# 7. (19)... soultoru(tw:soultoru)
# 10. (18)... holidayworking(tw:holidayworking)
#ggplot(join.rank, aes(y = reorder(Name, n), x = n)) + geom_point(size = join.rank$n / 2)

# Name2 <- c("yokkuns", "aad34210", "bob3", "teramonagi", "mikado_hito", "Hiro_macchan", 
#            "manozo", "atg", "soultoru", "holidayworking", "tetsuroito", "Prunus1350",
#            "teru3teru6", "kos59125", "otanet123", "sanoche16", "gepuro", "mitz321",
#            "azu-azu", "Y.Tokorosawa")

# ggplot(df.participation, aes(x = factor(1), fill = factor(n))) + geom_hist()
#  geom_bar(width = 1) +
#   coord_polar(theta = "y")
# group_by(df) %>% count(Twitter, sort = TRUE) %>% na.omit()
# https://atnd.org/users/5923
#summarise(df, tot = n(ID))
#d <- table(df$ID)
```

### 詳細はこちら

> Searchにユーザー名を入れて、気になる人の参加回数を表示できます

```{r}
datatable(df)
```

## 参加者における参加回数のヒストグラム

```{r, fig.align = 'center'}
ggplot(df.participation, aes(x = n)) + geom_histogram(binwidth = 1, fill = "#17CCB7") +
  theme_hc(bgcolor = "darkunica")
```


```{r call_api_from_json, eval=FALSE}
# JSON形式でATND apiを叩く
atnd <- getURL("http://api.atnd.org/events/?keyword=回R勉強会&owner_id=5923&owner_id=132547&owner_id=17358&count=51&format=json") %>%
  fromJSON()
str(atnd$events[1]) # リストの扱いわからん
```

## 参考

* [ATND API リファレンス](http://api.atnd.org/)
* [SASでATND APIからデータを取得する - Qiita](http://qiita.com/Prunus1350/items/fc58808a45b00bc0e25d)
* [政府統計の総合窓口(e-Stat)のAPIを使ってみよう [R編] - Qiita](http://qiita.com/R_Linux/items/e22d1ec28ab653f01f75)
* [rjsonではNULLデータをNAとして扱ってくれないらしい - 農業をITから考える頁](http://mi2yo4.blog136.fc2.com/blog-entry-81.html)