---
title: "Dataset: Japanese R Community"
author: "Shinya Uryu"
date: "February 15, 2015"
output: html_document
---

```{r using_pkg}
library("magrittr")
library("rvest")
library("dplyr", warn.conflicts = FALSE)
library("Nippon")
```

```{r DEFINE_FIUNCTION}
my.func <- function (start = NULL, times = NULL, num = NULL, turn = 4) {
  # df.text[start:end]
  # times... number of session
  # num... 何(#)回目？
  end <- start + times * turn - 1
  df.text[start:end] %>% 
    unlist() %>% 
    matrix(ncol = turn, byrow = TRUE) %>% 
    data.frame() %>% 
    transform(Number = num, Session = 1:nrow(.))
}

my.func2 <- function (start, end, num, turn = 4) {
  df.text[start:end] %>% 
    unlist() %>% 
    matrix(ncol = turn, byrow = TRUE) %>% 
    data.frame() %>% 
    transform(Number = num, Session = 1:nrow(.))
}

my.func3 <- function (num = NULL) {
  html(event$url[num]) %>% 
  html_nodes("table td") %>% 
  html_text() %>% 
  grep("[[:digit:]] – [[:digit:]]", ., value = TRUE, invert = TRUE) %>% 
  matrix(ncol = 2, byrow = TRUE) %>% 
  data.frame() %>% 
  transform(Number = num, Session = 1:nrow(.))
}

# Remove whitespace function
# ref) http://stackoverflow.com/questions/2261079/how-to-trim-leading-and-trailing-whitespace-in-r
trim <- function (x) {
  gsub("^\\s+|\\s+$", "", x)
}
```

データソース

* `source1`...http://lab.sakaue.info/wiki.cgi/JapanR2010?page=%CA%D9%B6%AF%B2%F1%C8%AF%C9%BD%C6%E2%CD%C6%B0%EC%CD%F7
* `source2`... http://estrellita.hatenablog.com
* `source3` (ATND)... 

```{r SET_SOURCE1}
df.source <- html("http://lab.sakaue.info/wiki.cgi/JapanR2010?page=%CA%D9%B6%AF%B2%F1%C8%AF%C9%BD%C6%E2%CD%C6%B0%EC%CD%F7")%>% 
  html_nodes("table td")
df.source <- df.source[1:1347]
df.text <- html_text(df.source) # Nagoya, Tsukuba, Tokyo
# df.url <- html_nodes(df.source, "a") %>% html_attr("href") # とっておく
```

# Tokyo.R

```{r}
df.tokyo <- my.func(207, 12, 35) %>% rbind(my.func(255, 7, 34)) %>% rbind(my.func(283, 17, 33)) %>% 
  rbind(my.func(351, 11, 32)) %>% rbind(my.func(395, 12, 31)) %>% rbind(my.func(443, 13, 30)) %>% 
  rbind(my.func(495, 13, 29)) %>% rbind(my.func(547, 12, 28)) %>% rbind(my.func(595, 5, 27)) %>% 
  rbind(my.func2(615, 630, 26)) %>% # 26回のみ仕様変更。手動で変更する必要あり
  rbind(my.func(632, 10, 25)) %>% rbind(my.func(672, 7, 24))
# テーブルの構造が変わるので一旦区切る
# table(df.tokyo$X1) # 確認用
colnames(df.tokyo) <- c("Speaker", "Title", "tmp", "Slide", "Number", "Session")

df.tokyo2 <- my.func(700, 11, 23) %>% rbind(my.func(744, 10, 22)) %>% rbind(my.func(784, 12, 21)) %>% 
  rbind(my.func(832, 8, 20)) %>% rbind(my.func(896, 6, 19)) %>% rbind(my.func(920, 8, 18)) %>% 
  rbind(my.func(952, 10, 17)) %>% rbind(my.func(992, 8, 16)) %>% rbind(my.func(1024, 7, 15)) %>% 
  rbind(my.func(1052, 8, 14)) %>% rbind(my.func(1084, 6, 13)) %>% rbind(my.func(1108, 6, 12)) %>% 
  rbind(my.func(1132, 6, 11)) %>% rbind(my.func(1156, 5, 10)) %>% rbind(my.func(1176, 5, 9)) %>% 
  rbind(my.func(1196, 5, 8)) %>% rbind(my.func(1216, 6, 7)) %>% rbind(my.func(1240, 6, 6)) %>% 
  rbind(my.func(1264, 4, 5)) %>% rbind(my.func(1280, 5, 4)) %>% rbind(my.func(1300, 6, 3)) %>% 
  rbind(my.func(1324, 3, 2)) %>% rbind(my.func(1336, 3, 1))
df.tokyo2 <- df.tokyo2[, c(2, 1, 3, 4, 5, 6)] # 列の並び替え（df.tokyoと統一）
colnames(df.tokyo2) <- c("Speaker", "Title", "tmp", "Slide", "Number", "Session")

df.tokyo %<>% rbind(df.tokyo2) # ２つのデータフレームを結合
df.tokyo <- df.tokyo[, c(5, 6, 1, 2, 4)]
rm(df.tokyo2)
```

手動確認作業

* Tokyo.R #26
* Speaker
    * うしろまえかわきよし、全角スペース
* 自己紹介の削除
    * Sessionの変更
* Title「(LT)」の削除
* Title「未定」と空白をNAに

```{r}
event <- read.csv("data/tokyor_event.csv", header = TRUE)
event$url %<>% as.character()
# browseURL(event$url[38])

df.tokyo3 <- my.func3(36) %>% rbind(my.func3(37)) %>% rbind(my.func3(38)) %>% rbind(my.func3(39)) %>% 
  rbind(my.func3(40)) %>% rbind(my.func3(41)) %>% rbind(my.func3(42)) %>% rbind(my.func3(43)) %>% 
  rbind(my.func3(44)) %>% rbind(my.func3(45)) %>% 
  transform(Slide = NA)
colnames(df.tokyo3) <- c("Speaker", "Title", "Number", "Session", "Slide")

df.tokyo3 <- df.tokyo3[, c(3, 4, 1, 2, 5)] # 列の並び替え（df.tokyoと統一）
```

```{r}
df.tokyo %<>% rbind(df.tokyo3)
rm(df.tokyo3)

# 修正
df.tokyo$Speaker %<>% zen2han()
df.tokyo$Title %<>% zen2han()

df.tokyo$Speaker %<>% str_replace_all("さん", "") %>% trim() # 「さん」づけの削除
df.tokyo$Speaker %<>% str_replace_all("@", "") # remove mention mark
# df.tokyo$Title %<>% str_replace_all("(LT)", "")
df.tokyo$Title %<>% str_replace_all("^[[:space:]]", "") # タイトルの前にあるスペースを削除（後ろにあるスペースも除きたいが..）
df.tokyo <- arrange(df.tokyo, Number, Session) %>% 
  transform(Community = "Tokyo.R")

# write.csv(df.tokyo, "data/tokyor_slide.csv", row.names = FALSE)
```
